name             'grubby'
maintainer       'Criteo'
maintainer_email 'j.mauro@criteo.com'
license          'Apache 2.0'
description      'Installs/Configures grubby'
long_description 'Installs/Configures grubby'
issues_url       'https://github.com/criteo-cookbooks/grubby'
source_url       'https://github.com/criteo-cookbooks/grubby'
version          '0.1.0'
supports         'centos'
